import pyaudio

# --- AUDIO STREAM SETTINGS ---
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 44100
CHUNK = 512

# --- FEEDBACK DETECTION SETTINGS ---
FEEDBACK_THRESHOLD_DB = -20
FEEDBACK_FREQ_MIN = 200
FEEDBACK_FREQ_MAX = 16000

# --- ALERT LEVELS ---
WARNING_THRESHOLD_DB = -25
CRITICAL_THRESHOLD_DB = -15